config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "devise/registrations" }

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'welcome#index', as: :unauthenticated_root
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  post '/stats' => 'game#update_stats', as: "stats"
  get 'welcome/index' => 'welcome#index', as: "unauth"
  get 'dashboard/leaderboard'
  get 'game/index' => 'game#index', as: "game"
  get 'game/guest_game' => 'game#guest_game', as: "guest_game"
  get 'players/:id' => 'players#show', as: "player"

  root :to => 'welcome#index'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def leaderboard
  end

  def index
    @users = User.all
    .order("high_score desc")
    .first(10)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_leaderboard.html.haml
%table{:border => "1"}
  %tr
    %th User
    %th High Score
  -users.each do |user|
    %tr
      %td=link_to user.username, player_path(id: user.id)
      %td= user.high_score

app/views/dashboard/index.html.haml
= link_to "Play Game", game_path, :class => "button", :onclick => "create(9,9,16, 'easy')"
.row
  .col-sm-4
    = render partial:  "dashboard/leaderboard", locals: {users: @users}

app/views/dashboard/leaderboard.html.haml
%h1 Dashboard#leaderboard
%p Find me in app/views/dashboard/leaderboard.html.haml